#ifdef BIN

#include "basic.h"
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#define OUTPUT_HEAD                                                            \
    ("// This file includes all other headers from the library at once.\n"     \
     "// This file is generated by `" __FILE__ "`.\n"                          \
     "\n"                                                                      \
     "// This line below tells clang-tidy to not emit warnings about unused "  \
     "includes.\n"                                                             \
     "// You would think the standard 'NOLINT' notation would work, but it's " \
     "bugged.\n"                                                               \
     "// IWYU pragma: begin_exports")

#define OUTPUT_TAIL "// IWYU pragma: end_exports"

bool is_file_readable(const char* path) {
    FILE* f = fopen(path, "r");
    if (f == NULL) return false;
    fclose(f);
    return true;
}

const char* get_file_name(const char* path) {
    const char* ret = strrchr(path, '/');
    if (ret == NULL) ret = strrchr(path, '\\');
    if (ret == NULL) return NULL;
    return ret + 1;
}

int main(int argc, const char** argv) {
    EXPECT(argc > 1, "no arguments???");
    // The first argument is a directory. The rest are names of files to
    // include. Make sure they all exist. The output is the contents of the
    // generated header.
    puts(OUTPUT_HEAD);
    for (int i = 1; i < argc; i++) {
        const char* file = argv[i];
        EXPECT(is_file_readable(file), "file '%s' could not be read", file);
        const char* name = get_file_name(file);
        EXPECT(name, "could not get file-name from path '%s'", file);
        printf("#include \"%s\"\n", name);
    }
    puts(OUTPUT_TAIL);
    return 0;
}

#else
int just_stop_complaining = 1;
#endif
